#!/bin/sh
BARCODE_IMAGE="/tmp/qr.png"

grim -g "$(slurp)" /tmp/qr.png

if [ $? -eq 0 ]; then
  SCANRESULT=$(zbarimg --quiet --raw "$BARCODE_IMAGE" | tr -d '\n')

  if [ -z "$SCANRESULT" ]; then
    notify-desktop "zbar" "No scan data found"
  else
    echo "$SCANRESULT" | wl-copy
    convert $BARCODE_IMAGE -resize 75x75 "$BARCODE_IMAGE"
    dunstify -i "$BARCODE_IMAGE" "zbar" "$SCANRESULT\n(copied to clipboard)"
  fi
fi
